# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb8e9ab2d5e7ade522c19ab3cc3b15cf3da12b874bd0e655e681dfdd7e159bff55e408393a4c8ff7790e97871de72372039a7a6c6e006438f51b6e56db29a3e0

test:
  secret_key_base: 384abddb7170c43d1297496af0d60cf14fe496366695e5cff7c8ca51a224cd7c4b1d5c9bbbd7e1f2b71927d7914eac0d2f50f9ed3e1708d62b54091888a1836a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
